In [3]:
import numpy as np
import pandas as pd

In [4]:
from selenium import webdriver
from selenium.webdriver.common.by import By

### Open the Website

In [5]:
driver = webdriver.Chrome()
driver.get("https://www.iplt20.com/stats/2025")

In [6]:
import numpy as np
import pandas as pd

POS = []
Player = []
GT = []
Runs = []
Mat = []
Inns = []
NO = []
HS = []
Avg = []
BF = []
SR = []
hundreds = []
fifties = []
fours = []
sixes = []

for i in range(1,158): 
    
    # -------- POSITION --------
    try:
        pos_val = driver.find_element(By.XPATH, f"/html/body/div[1]/div[2]/div[4]/div/section/div/div[3]/div[2]/div[2]/div/div[3]/div/div[1]/table/tbody/tr[{i}]/td[1]").text
        POS.append(pos_val)
    except:
        POS.append(np.nan)
    
    # -------- PLAYER NAME --------
    try:
        player_val = driver.find_element(By.XPATH, f"/html/body/div[1]/div[2]/div[4]/div/section/div/div[3]/div[2]/div[2]/div/div[3]/div/div[1]/table/tbody/tr[{i}]/td[2]/div/a/div[1]").text
        Player.append(player_val)
    except:
        Player.append(np.nan)
    
    # -------- TEAM --------
    try:
        team_val = driver.find_element(By.XPATH, f"/html/body/div[1]/div[2]/div[4]/div/section/div/div[3]/div[2]/div[2]/div/div[3]/div/div[1]/table/tbody/tr[{i}]/td[2]/div/a/div[2]").text
        GT.append(team_val)
    except:
        GT.append(np.nan)
    
    # -------- RUNS SCORED --------
    try:
        runs_val = driver.find_element(By.XPATH, f"/html/body/div[1]/div[2]/div[4]/div/section/div/div[3]/div[2]/div[2]/div/div[3]/div/div[1]/table/tbody/tr[{i}]/td[3]").text
        Runs.append(runs_val)
    except:
        Runs.append(np.nan)
    
    # -------- MATCHES --------
    try:
        mat_val = driver.find_element(By.XPATH, f"/html/body/div[1]/div[2]/div[4]/div/section/div/div[3]/div[2]/div[2]/div/div[3]/div/div[1]/table/tbody/tr[{i}]/td[4]").text
        Mat.append(mat_val)
    except:
        Mat.append(np.nan)
    
    # -------- INNINGS --------
    try:
        inns_val = driver.find_element(By.XPATH, f"/html/body/div[1]/div[2]/div[4]/div/section/div/div[3]/div[2]/div[2]/div/div[3]/div/div[1]/table/tbody/tr[{i}]/td[5]").text
        Inns.append(inns_val)
    except:
        Inns.append(np.nan)
    
    # -------- NOT OUTS --------
    try:
        no_val = driver.find_element(By.XPATH, f"/html/body/div[1]/div[2]/div[4]/div/section/div/div[3]/div[2]/div[2]/div/div[3]/div/div[1]/table/tbody/tr[{i}]/td[6]").text
        NO.append(no_val)
    except:
        NO.append(np.nan)
    
    # -------- HIGHEST SCORE --------
    try:
        hs_val = driver.find_element(By.XPATH, f"/html/body/div[1]/div[2]/div[4]/div/section/div/div[3]/div[2]/div[2]/div/div[3]/div/div[1]/table/tbody/tr[{i}]/td[7]").text
        HS.append(hs_val)
    except:
        HS.append(np.nan)
    
    # -------- BATTING AVERAGE --------
    try:
        avg_val = driver.find_element(By.XPATH, f"/html/body/div[1]/div[2]/div[4]/div/section/div/div[3]/div[2]/div[2]/div/div[3]/div/div[1]/table/tbody/tr[{i}]/td[8]").text
        Avg.append(avg_val)
    except:
        Avg.append(np.nan)
    
    # -------- BALLS FACED --------
    try:
        bf_val = driver.find_element(By.XPATH, f"/html/body/div[1]/div[2]/div[4]/div/section/div/div[3]/div[2]/div[2]/div/div[3]/div/div[1]/table/tbody/tr[{i}]/td[9]").text
        BF.append(bf_val)
    except:
        BF.append(np.nan)
    
    # -------- STRIKE RATE --------
    try:
        sr_val = driver.find_element(By.XPATH, f"/html/body/div[1]/div[2]/div[4]/div/section/div/div[3]/div[2]/div[2]/div/div[3]/div/div[1]/table/tbody/tr[{i}]/td[10]").text
        SR.append(sr_val)
    except:
        SR.append(np.nan)
    
    # -------- CENTURIES --------
    try:
        hundreds_val = driver.find_element(By.XPATH, f"/html/body/div[1]/div[2]/div[4]/div/section/div/div[3]/div[2]/div[2]/div/div[3]/div/div[1]/table/tbody/tr[{i}]/td[11]").text
        hundreds.append(hundreds_val)
    except:
        hundreds.append(np.nan)
    
    # -------- FIFTIES --------
    try:
        fifties_val = driver.find_element(By.XPATH, f"/html/body/div[1]/div[2]/div[4]/div/section/div/div[3]/div[2]/div[2]/div/div[3]/div/div[1]/table/tbody/tr[{i}]/td[12]").text
        fifties.append(fifties_val)
    except:
        fifties.append(np.nan)
    
    # -------- NUMBER OF FOURS --------
    try:
        fours_val = driver.find_element(By.XPATH, f"/html/body/div[1]/div[2]/div[4]/div/section/div/div[3]/div[2]/div[2]/div/div[3]/div/div[1]/table/tbody/tr[{i}]/td[13]").text
        fours.append(fours_val)
    except:
        fours.append(np.nan)
    
    # -------- NUMBER OF SIXES --------
    try:
        sixes_val = driver.find_element(By.XPATH, f"/html/body/div[1]/div[2]/div[4]/div/section/div/div[3]/div[2]/div[2]/div/div[3]/div/div[1]/table/tbody/tr[{i}]/td[14]").text
        sixes.append(sixes_val)
    except:
        sixes.append(np.nan)

print("!! Data successfully extracted !!")

ipl_dict={'POS':POS,'Player':Player,'GT':GT,'Runs':Runs,
          'Mat':Mat,'Inns':Inns,'NO':NO,'HS':HS,
          'Avg':Avg,'BF':BF,'SR':SR,'hundreds':hundreds,
          'fifties':fifties,'fours':fours,'sixes':sixes}

df_ipl = pd.DataFrame(ipl_dict)
df_ipl.to_csv(f'ipl_data.csv',index=False)

!! Data successfully extracted !!

In [13]:
driver.quit()

In [88]:
ipl_dict={'POS':POS,'Player':Player,'GT':GT,'Runs':Runs,
          'Mat':Mat,'Inns':Inns,'NO':NO,'HS':HS,
          'Avg':Avg,'BF':BF,'SR':SR,'hundreds':hundreds,
          'fifties':fifties,'fours':fours,'sixes':sixes}

df_ipl = pd.DataFrame(ipl_dict)

### Extracted Data

In [89]:
df_ipl

,POS,Player,GT,Runs,Mat,Inns,NO,HS,Avg,BF,SR,hundreds,fifties,fours,sixes
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
2,2,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
3,3,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
4,4,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,152,Khaleel Ahmed,CSK,1,14,2,2,1*,-,2,50.00,0,0,0,0
153,153,Mohit Sharma,DC,1,8,2,1,1*,1.00,3,33.33,0,0,0,0
154,154,Donovan Ferreira,DC,1,1,1,0,1,1.00,3,33.33,0,0,0,0
155,155,Digvesh Singh,LSG,1,13,2,1,1,1.00,3,33.33,0,0,0,0
156,156,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0

### Removing Null Value

In [90]:
df_ipl.dropna(axis = 0,how='all',inplace=True)

In [91]:
df_ipl

,POS,Player,GT,Runs,Mat,Inns,NO,HS,Avg,BF,SR,hundreds,fifties,fours,sixes
1,1,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
2,2,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
3,3,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
4,4,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
5,5,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,152,Khaleel Ahmed,CSK,1,14,2,2,1*,-,2,50.00,0,0,0,0
153,153,Mohit Sharma,DC,1,8,2,1,1*,1.00,3,33.33,0,0,0,0
154,154,Donovan Ferreira,DC,1,1,1,0,1,1.00,3,33.33,0,0,0,0
155,155,Digvesh Singh,LSG,1,13,2,1,1,1.00,3,33.33,0,0,0,0
156,156,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0

### Converting the DataType into integer and float

In [92]:
df_ipl["HS"] = df_ipl["HS"].str.replace('*','')

In [93]:
df_ipl["Avg"]=df_ipl["Avg"].str.replace('-','0')

In [94]:
list1 = ["Runs", "Mat", "Inns", "NO", "HS", "BF", "hundreds", "fifties", "fours", "sixes"]
for item in list1:
    df_ipl[item] = df_ipl[item].astype(int)

list2 = ["Avg", "SR"]
for item in list2:
    df_ipl[item] = df_ipl[item].astype(float)

In [95]:
df_ipl

,POS,Player,GT,Runs,Mat,Inns,NO,HS,Avg,BF,SR,hundreds,fifties,fours,sixes
1,1,Sai Sudharsan,GT,759,15,15,1,108,54.21,486,156.17,1,6,88,21
2,2,Surya Kumar Yadav,MI,717,16,16,5,73,65.18,427,167.91,0,5,69,38
3,3,Virat Kohli,RCB,657,15,15,3,73,54.75,454,144.71,0,8,66,19
4,4,Shubman Gill,GT,650,15,15,2,93,50.00,417,155.87,0,6,62,24
5,5,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,152,Khaleel Ahmed,CSK,1,14,2,2,1,0.00,2,50.00,0,0,0,0
153,153,Mohit Sharma,DC,1,8,2,1,1,1.00,3,33.33,0,0,0,0
154,154,Donovan Ferreira,DC,1,1,1,0,1,1.00,3,33.33,0,0,0,0
155,155,Digvesh Singh,LSG,1,13,2,1,1,1.00,3,33.33,0,0,0,0
156,156,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0