In [1]:
import pandas as pd
import numpy as np

In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By

In [3]:
import math
import time
import pickle

### Open the Website

In [4]:
driver = webdriver.Chrome()
driver.get("https://www.iplt20.com/points-table/men/2025")

In [5]:
data=driver.find_element(By.XPATH,'/html/body/div[1]/section/div/div/div[1]/div/div/div[1]/div/div/div[2]/div/div/div/table').text
data

'POS TEAM P W L NR NRR FOR AGAINST PTS RECENT FORM\n1\nPBKS\n14 9 4 1 0.372 2447/246.4 2395/250.5 19\nW\nL\nW\nW\nW\n2\nRCB\n14 9 4 1 0.301 2357/243.5 2321/247.5 19\nW\nL\nN\nW\nW\n3\nGT\n14 9 5 0 0.254 2684/271.5 2639/274.2 18\nL\nL\nW\nW\nW\n4\nMI\n14 8 6 0 1.142 2472/261.2 2301/276.4 16\nL\nW\nL\nW\nW\n5\nDC\n14 7 6 1 0.011 2354/250.4 2409/256.5 15\nW\nL\nL\nN\nL\n6\nSRH\n14 6 7 1 -0.241 2519/255.3 2451/242.4 13\nW\nW\nW\nN\nL\n7\nLSG\n14 6 8 0 -0.376 2732/275.4 2779/270.1 12\nL\nW\nL\nL\nL\n8\nKKR\n14 5 7 2 -0.305 1995/227.4 2075/228.5 12\nL\nN\nL\nW\nW\n9\nRR\n14 4 10 0 -0.549 2603/273.0 2773/275.0 8\nW\nL\nL\nL\nW\n10\nCSK\n14 4 10 0 -0.647 2441/278.2 2461/261.2 8\nW\nL\nW\nL\nL'

In [101]:
columns = data.split('\n')[0].split(" ")
columns

['POS',
 'TEAM',
 'P',
 'W',
 'L',
 'NR',
 'NRR',
 'FOR',
 'AGAINST',
 'PTS',
 'RECENT',
 'FORM']

In [102]:
cols = columns[:-2] + [' '.join(columns[-1:-3:-1][::-1])]
cols

['POS',
 'TEAM',
 'P',
 'W',
 'L',
 'NR',
 'NRR',
 'FOR',
 'AGAINST',
 'PTS',
 'RECENT FORM']

In [103]:
data_list = data.split("\n")[1:]
data_list[0:8]

['1',
 'PBKS',
 '14 9 4 1 0.372 2447/246.4 2395/250.5 19',
 'W',
 'L',
 'W',
 'W',
 'W']

In [104]:
arr = np.array(data_list)
arr.reshape(10,8)

array([['1', 'PBKS', '14 9 4 1 0.372 2447/246.4 2395/250.5 19', 'W', 'L',
        'W', 'W', 'W'],
       ['2', 'RCB', '14 9 4 1 0.301 2357/243.5 2321/247.5 19', 'W', 'L',
        'N', 'W', 'W'],
       ['3', 'GT', '14 9 5 0 0.254 2684/271.5 2639/274.2 18', 'L', 'L',
        'W', 'W', 'W'],
       ['4', 'MI', '14 8 6 0 1.142 2472/261.2 2301/276.4 16', 'L', 'W',
        'L', 'W', 'W'],
       ['5', 'DC', '14 7 6 1 0.011 2354/250.4 2409/256.5 15', 'W', 'L',
        'L', 'N', 'L'],
       ['6', 'SRH', '14 6 7 1 -0.241 2519/255.3 2451/242.4 13', 'W', 'W',
        'W', 'N', 'L'],
       ['7', 'LSG', '14 6 8 0 -0.376 2732/275.4 2779/270.1 12', 'L', 'W',
        'L', 'L', 'L'],
       ['8', 'KKR', '14 5 7 2 -0.305 1995/227.4 2075/228.5 12', 'L', 'N',
        'L', 'W', 'W'],
       ['9', 'RR', '14 4 10 0 -0.549 2603/273.0 2773/275.0 8', 'W', 'L',
        'L', 'L', 'W'],
       ['10', 'CSK', '14 4 10 0 -0.647 2441/278.2 2461/261.2 8', 'W',
        'L', 'W', 'L', 'L']], dtype='<U40')

In [107]:
arr=np.array(data_list)
df=pd.DataFrame(arr.reshape((int(arr.shape[0] / 8)), 8))
df

    0     1                                         2  3  4  5  6  7
0   1  PBKS   14 9 4 1 0.372 2447/246.4 2395/250.5 19  W  L  W  W  W
1   2   RCB   14 9 4 1 0.301 2357/243.5 2321/247.5 19  W  L  N  W  W
2   3    GT   14 9 5 0 0.254 2684/271.5 2639/274.2 18  L  L  W  W  W
3   4    MI   14 8 6 0 1.142 2472/261.2 2301/276.4 16  L  W  L  W  W
4   5    DC   14 7 6 1 0.011 2354/250.4 2409/256.5 15  W  L  L  N  L
5   6   SRH  14 6 7 1 -0.241 2519/255.3 2451/242.4 13  W  W  W  N  L
6   7   LSG  14 6 8 0 -0.376 2732/275.4 2779/270.1 12  L  W  L  L  L
7   8   KKR  14 5 7 2 -0.305 1995/227.4 2075/228.5 12  L  N  L  W  W
8   9    RR  14 4 10 0 -0.549 2603/273.0 2773/275.0 8  W  L  L  L  W
9  10   CSK  14 4 10 0 -0.647 2441/278.2 2461/261.2 8  W  L  W  L  L

In [108]:
df[2].str.split(expand=True)

    0  1   2  3       4           5           6   7
0  14  9   4  1   0.372  2447/246.4  2395/250.5  19
1  14  9   4  1   0.301  2357/243.5  2321/247.5  19
2  14  9   5  0   0.254  2684/271.5  2639/274.2  18
3  14  8   6  0   1.142  2472/261.2  2301/276.4  16
4  14  7   6  1   0.011  2354/250.4  2409/256.5  15
5  14  6   7  1  -0.241  2519/255.3  2451/242.4  13
6  14  6   8  0  -0.376  2732/275.4  2779/270.1  12
7  14  5   7  2  -0.305  1995/227.4  2075/228.5  12
8  14  4  10  0  -0.549  2603/273.0  2773/275.0   8
9  14  4  10  0  -0.647  2441/278.2  2461/261.2   8

In [109]:
df[cols[2:10]]=df[2].str.split(expand=True)

In [110]:
df.drop(columns=2,inplace=True)

In [111]:
df

    0     1  3  4  5  6  7   P  W   L NR     NRR         FOR     AGAINST PTS
0   1  PBKS  W  L  W  W  W  14  9   4  1   0.372  2447/246.4  2395/250.5  19
1   2   RCB  W  L  N  W  W  14  9   4  1   0.301  2357/243.5  2321/247.5  19
2   3    GT  L  L  W  W  W  14  9   5  0   0.254  2684/271.5  2639/274.2  18
3   4    MI  L  W  L  W  W  14  8   6  0   1.142  2472/261.2  2301/276.4  16
4   5    DC  W  L  L  N  L  14  7   6  1   0.011  2354/250.4  2409/256.5  15
5   6   SRH  W  W  W  N  L  14  6   7  1  -0.241  2519/255.3  2451/242.4  13
6   7   LSG  L  W  L  L  L  14  6   8  0  -0.376  2732/275.4  2779/270.1  12
7   8   KKR  L  N  L  W  W  14  5   7  2  -0.305  1995/227.4  2075/228.5  12
8   9    RR  W  L  L  L  W  14  4  10  0  -0.549  2603/273.0  2773/275.0   8
9  10   CSK  W  L  W  L  L  14  4  10  0  -0.647  2441/278.2  2461/261.2   8

In [112]:
recent_form=[]
for item in np.array(df.iloc[:,2:7]):
    recent_form.append('-'.join(item))

In [113]:
recent_form

['W-L-W-W-W',
 'W-L-N-W-W',
 'L-L-W-W-W',
 'L-W-L-W-W',
 'W-L-L-N-L',
 'W-W-W-N-L',
 'L-W-L-L-L',
 'L-N-L-W-W',
 'W-L-L-L-W',
 'W-L-W-L-L']

In [114]:
df['recent_form'] = recent_form

In [115]:
df.drop(columns=[i for i in range(3,8)],inplace=True)

In [116]:
df.columns=cols

In [117]:
df

  POS  TEAM   P  W   L NR     NRR         FOR     AGAINST PTS RECENT FORM
0   1  PBKS  14  9   4  1   0.372  2447/246.4  2395/250.5  19   W-L-W-W-W
1   2   RCB  14  9   4  1   0.301  2357/243.5  2321/247.5  19   W-L-N-W-W
2   3    GT  14  9   5  0   0.254  2684/271.5  2639/274.2  18   L-L-W-W-W
3   4    MI  14  8   6  0   1.142  2472/261.2  2301/276.4  16   L-W-L-W-W
4   5    DC  14  7   6  1   0.011  2354/250.4  2409/256.5  15   W-L-L-N-L
5   6   SRH  14  6   7  1  -0.241  2519/255.3  2451/242.4  13   W-W-W-N-L
6   7   LSG  14  6   8  0  -0.376  2732/275.4  2779/270.1  12   L-W-L-L-L
7   8   KKR  14  5   7  2  -0.305  1995/227.4  2075/228.5  12   L-N-L-W-W
8   9    RR  14  4  10  0  -0.549  2603/273.0  2773/275.0   8   W-L-L-L-W
9  10   CSK  14  4  10  0  -0.647  2441/278.2  2461/261.2   8   W-L-W-L-L

In [118]:
for i in cols[2:6]:
    df[i]=df[i].astype(int)
df['NRR']=df['NRR'].apply(lambda x : float(x))
df['PTS']=df['PTS'].apply(lambda x : int(x))

In [119]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   POS          10 non-null     object
 1   TEAM         10 non-null     object
 2   P            10 non-null     int64
 3   W            10 non-null     int64
 4   L            10 non-null     int64
 5   NR           10 non-null     int64
 6   NRR          10 non-null     float64
 7   FOR          10 non-null     object
 8   AGAINST      10 non-null     object
 9   PTS          10 non-null     int64
 10  RECENT FORM  10 non-null     object
dtypes: float64(1), int64(5), object(5)
memory usage: 1012.0+ bytes

In [120]:
df

  POS  TEAM   P  W   L  NR    NRR         FOR     AGAINST  PTS RECENT FORM
0   1  PBKS  14  9   4   1  0.372  2447/246.4  2395/250.5   19   W-L-W-W-W
1   2   RCB  14  9   4   1  0.301  2357/243.5  2321/247.5   19   W-L-N-W-W
2   3    GT  14  9   5   0  0.254  2684/271.5  2639/274.2   18   L-L-W-W-W
3   4    MI  14  8   6   0  1.142  2472/261.2  2301/276.4   16   L-W-L-W-W
4   5    DC  14  7   6   1  0.011  2354/250.4  2409/256.5   15   W-L-L-N-L
5   6   SRH  14  6   7   1 -0.241  2519/255.3  2451/242.4   13   W-W-W-N-L
6   7   LSG  14  6   8   0 -0.376  2732/275.4  2779/270.1   12   L-W-L-L-L
7   8   KKR  14  5   7   2 -0.305  1995/227.4  2075/228.5   12   L-N-L-W-W
8   9    RR  14  4  10   0 -0.549  2603/273.0  2773/275.0    8   W-L-L-L-W
9  10   CSK  14  4  10   0 -0.647  2441/278.2  2461/261.2    8   W-L-W-L-L

### Creating Custom Function

In [121]:
def create_df(data):
    columns = data.split('\n')[0].split(" ")
    cols = columns[:-2] + [' '.join(columns[-1:-3:-1][::-1])]
    data_list = data.split("\n")[1:]
    arr=np.array(data_list)
    df=pd.DataFrame(arr.reshape((int(arr.shape[0] / 8)), 8))
    
    df[cols[2:10]]=df[2].str.split(expand=True)
    df.drop(columns=2,inplace=True)
    
    recent_form=[]
    for item in np.array(df.iloc[:,2:7]):
        recent_form.append('-'.join(item))
    df['recent_form'] = recent_form
    
    df.drop(columns=[i for i in range(3,8)],inplace=True)
    df.columns=cols
    
    for i in cols[2:6]:
        df[i]=df[i].astype(int)
    df['NRR']=df['NRR'].apply(lambda x : float(x))
    df['PTS']=df['PTS'].apply(lambda x : int(x))
    
    return df

In [122]:
create_df(data)

  POS  TEAM   P  W   L  NR    NRR         FOR     AGAINST  PTS RECENT FORM
0   1  PBKS  14  9   4   1  0.372  2447/246.4  2395/250.5   19   W-L-W-W-W
1   2   RCB  14  9   4   1  0.301  2357/243.5  2321/247.5   19   W-L-N-W-W
2   3    GT  14  9   5   0  0.254  2684/271.5  2639/274.2   18   L-L-W-W-W
3   4    MI  14  8   6   0  1.142  2472/261.2  2301/276.4   16   L-W-L-W-W
4   5    DC  14  7   6   1  0.011  2354/250.4  2409/256.5   15   W-L-L-N-L
5   6   SRH  14  6   7   1 -0.241  2519/255.3  2451/242.4   13   W-W-W-N-L
6   7   LSG  14  6   8   0 -0.376  2732/275.4  2779/270.1   12   L-W-L-L-L
7   8   KKR  14  5   7   2 -0.305  1995/227.4  2075/228.5   12   L-N-L-W-W
8   9    RR  14  4  10   0 -0.549  2603/273.0  2773/275.0    8   W-L-L-L-W
9  10   CSK  14  4  10   0 -0.647  2441/278.2  2461/261.2    8   W-L-W-L-L